// Response from querying "Search under folder"
export default {
  docResult: [
    {
      metadata: {
        "File Type Detail": "SVG",
        "File Type Extension": "svg",
        "Flight File Extension": "svg",
        WHRotated: "false",
        "View Box": "0 0 298.8 825.5",
        Style: "enable-background:new 0 0 298.8 825.5;",
        RSize: "934",
        "Flight File Type": "svg",
        "File Name": "neutral.svg",
        ID: "Layer_1",
        "Create Date": "2023-09-20 13:45:06",
        "original Width": "280",
        "File Inode Change Date/Time": "2023-09-20 13:45:06",
        "File Type": "image",
        "Image Size": "934x2580",
        "File Access Date/Time": "2023-09-20 13:45:06",
        "Image Height": "2580",
        Orientation: "Portrait File",
        "Image Width": "934",
        "File Modification Date/Time": "2023-09-20 13:45:06",
        "MIME Type": "image/svg+xml",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "11678",
        Xmlns: "http://www.w3.org/2000/svg",
        "SVG Version": "1.1",
        "original Height": "774",
        "Tag Y": "0px",
        Panoramas: "false",
        "Tag X": "0px",
      },
      smartTags: [
        "Adult",
        "Dress",
        "Face",
        "Female",
        "Head",
        "Lady",
        "Long Sleeve",
        "Person",
        "Sleeve",
        "Woman",
      ],
      ownerName: "cmarsh@idems.international",
      dpi: "72",
      height: "2580",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/S9CBS/H45JP/JN6JU/TDEJQ",
          namePath: "debug folder/ParentApp for Teens TZ/images/characters/neighbour",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/TDEJQ" },
          width: "0",
          name: "neighbour",
          id: "TDEJQ",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "8872a54ec15b8148b36382c161721d4e",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230920064506677",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      lastUploaded: "20230920064506677",
      created: "20230920064506677",
      time: "20230920064506677",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/383q8ogklt5ft4ckadacjj826b/pYIoWOvLyezOQNIj_3cnCRFRz9w/original?content-type=image%2Fsvg%2Bxml&name=neutral.svg",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=383q8ogklt5ft4ckadacjj826b",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/383q8ogklt5ft4ckadacjj826b/gnaIz3qbZocX0cSDAyr3Qmc4PbU/m800/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "934",
      name: "neutral.svg",
      default: {
        Size: "11678",
        Color: null,
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "934*2580 Pixels",
        GPS: null,
        "Date uploaded": "20230920064506677",
        "Date modified": "20230920064506677",
        Name: "neutral.svg",
        "Modified by": null,
        "Content Type": "image/svg+xml",
        Author: null,
        "Date Created": "2023-09-20 13:45:06",
        Resolution: null,
      },
      id: "383q8ogklt5ft4ckadacjj826b",
      size: "11678",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      metadata: {
        "Rendering Intent": "Perceptual",
        "Video Card Gamma": "(Binary data 48 bytes, use -b option to extract)",
        Compression: "Deflate/Inflate",
        "File Type Detail": "PNG",
        "File Type Extension": "png",
        "Profile ID": "0",
        "Profile Description ML (hi-IN)": "रंगीन LCD",
        "Pixel Units": "meters",
        "Profile Copyright": "Copyright Apple Inc., 2023",
        RDpi: "144",
        "X Resolution": "144",
        "Profile Date Time": "2023-06-22 09:28:22",
        "Profile File Signature": "acsp",
        "Profile Creator": "Apple Computer Inc.",
        WHRotated: "false",
        "Primary Platform": "Apple Computer Inc.",
        "CMM Flags": "Not Embedded, Independent",
        "Create Date": "2023-09-20 10:59:15",
        "Exif Byte Order": "Big-endian (Motorola, MM)",
        "User Comment": "Screenshot",
        "File Inode Change Date/Time": "2023-09-20 10:59:15",
        Color: "RGB",
        "Color Mode": "RGB",
        "Pixels Per Unit X": "5669",
        "File Type": "image",
        "Profile Version": "2.1.0",
        "Profile Description ML (fr-CA)": "ACL couleur",
        "Pixels Per Unit Y": "5669",
        "Color Model": "RGB",
        "Image Size": "44x58",
        "File Access Date/Time": "2023-09-20 10:59:15",
        Orientation: "Portrait File",
        "Profile Description ML (vi-VN)": "LCD Màu",
        "File Modification Date/Time": "2023-09-20 10:59:15",
        "Profile Description ML (en-GB)": "Colour LCD",
        Megapixels: "0.003",
        Interlace: "Noninterlaced",
        "Exif Image Height": "58",
        "Profile Description ML": "Color LCD",
        "Profile Connection Space": "XYZ",
        "Blue Matrix Column": "0.1571 0.06657 0.78407",
        "Y Resolution": "144",
        "Flight File Extension": "png",
        "Profile Description": "Display",
        "Profile Description ML (pt-PT)": "LCD a cores",
        "Device Manufacturer": "Apple Computer Inc.",
        "Color Space": "RGB",
        "Profile Name": "ICC Profile",
        RSize: "44",
        "Red Matrix Column": "0.51512 0.2412 -0.00105",
        "Flight File Type": "png",
        "File Name": "image 1.png",
        "Profile Class": "Display Device Profile",
        "Native Display Info": "(Binary data 62 bytes, use -b option to extract)",
        "Media White Point": "0.95045 1 1.08905",
        "Profile CMM Type": "Apple Computer Inc.",
        "Profile Description ML (es-XL)": "LCD color",
        "Bit Depth": "8",
        "Exif Image Width": "44",
        "Profile Description ML (en-AU)": "Colour LCD",
        "Image Height": "58",
        "Connection Space Illuminant": "0.9642 1 0.82491",
        "Image Width": "44",
        "Resolution Unit": "inches",
        "MIME Type": "image/png",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "4895",
        Filter: "Adaptive",
        "XMP Toolkit": "XMP Core 6.0.0",
        "Green Matrix Column": "0.29198 0.69225 0.04189",
        "Profile Description ML (fr-FR)": "LCD couleur",
        "Device Attributes": "Reflective, Glossy, Positive, Color",
        Panoramas: "false",
      },
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "58",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          name: "debug album",
          id: "GT7AG",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "ddf11cfc55671f90963001799d169807",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230920035915754",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      lastUploaded: "20230920035915754",
      created: "20230920035915754",
      time: "20230920035949977",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/vil7vn2g513ajfcr2ppgmd5c0a/ylpbwhrK2M8BLdjdt7PMchPk4tk/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=vil7vn2g513ajfcr2ppgmd5c0a",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/vil7vn2g513ajfcr2ppgmd5c0a/xTtaCIRdgRgpy3WR_ZpLidb9Ng4/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "44",
      name: "image 1.png",
      default: {
        Size: "4895",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "44*58 Pixels",
        GPS: null,
        "Date uploaded": "20230920035915754",
        "Date modified": "20230920035949977",
        Name: "image 1.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-09-20 10:59:15",
        Resolution: "144",
      },
      id: "vil7vn2g513ajfcr2ppgmd5c0a",
      size: "4895",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      metadata: {
        "Rendering Intent": "Perceptual",
        "Video Card Gamma": "(Binary data 48 bytes, use -b option to extract)",
        Compression: "Deflate/Inflate",
        "File Type Detail": "PNG",
        "File Type Extension": "png",
        "Profile ID": "0",
        "Profile Description ML (hi-IN)": "रंगीन LCD",
        "Pixel Units": "meters",
        "Profile Copyright": "Copyright Apple Inc., 2023",
        RDpi: "144",
        "X Resolution": "144",
        "Profile Date Time": "2023-06-22 09:28:22",
        "Profile File Signature": "acsp",
        "Profile Creator": "Apple Computer Inc.",
        WHRotated: "false",
        "Primary Platform": "Apple Computer Inc.",
        "CMM Flags": "Not Embedded, Independent",
        "Create Date": "2023-08-25 11:35:25",
        "Exif Byte Order": "Big-endian (Motorola, MM)",
        "User Comment": "Screenshot",
        "File Inode Change Date/Time": "2023-08-25 11:35:25",
        Color: "RGB",
        "Color Mode": "RGB",
        "Pixels Per Unit X": "5669",
        "File Type": "image",
        "Profile Version": "2.1.0",
        "Profile Description ML (fr-CA)": "ACL couleur",
        "Pixels Per Unit Y": "5669",
        "Color Model": "RGB",
        "Image Size": "44x58",
        "File Access Date/Time": "2023-08-25 11:35:25",
        Orientation: "Portrait File",
        "Profile Description ML (vi-VN)": "LCD Màu",
        "File Modification Date/Time": "2023-08-25 11:35:25",
        "Profile Description ML (en-GB)": "Colour LCD",
        Megapixels: "0.003",
        Interlace: "Noninterlaced",
        "Exif Image Height": "58",
        "Profile Description ML": "Color LCD",
        "Profile Connection Space": "XYZ",
        "Blue Matrix Column": "0.1571 0.06657 0.78407",
        "Y Resolution": "144",
        "Flight File Extension": "png",
        "Profile Description": "Display",
        "Profile Description ML (pt-PT)": "LCD a cores",
        "Device Manufacturer": "Apple Computer Inc.",
        "Color Space": "RGB",
        "Profile Name": "ICC Profile",
        RSize: "44",
        "Red Matrix Column": "0.51512 0.2412 -0.00105",
        "Flight File Type": "png",
        "File Name": "unhelpful_name.png",
        "Profile Class": "Display Device Profile",
        "Native Display Info": "(Binary data 62 bytes, use -b option to extract)",
        "Media White Point": "0.95045 1 1.08905",
        "Profile CMM Type": "Apple Computer Inc.",
        "Profile Description ML (es-XL)": "LCD color",
        "Bit Depth": "8",
        "Exif Image Width": "44",
        "Profile Description ML (en-AU)": "Colour LCD",
        "Image Height": "58",
        "Connection Space Illuminant": "0.9642 1 0.82491",
        "Image Width": "44",
        "Resolution Unit": "inches",
        "MIME Type": "image/png",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "4895",
        Filter: "Adaptive",
        "XMP Toolkit": "XMP Core 6.0.0",
        "Green Matrix Column": "0.29198 0.69225 0.04189",
        "Profile Description ML (fr-FR)": "LCD couleur",
        "Device Attributes": "Reflective, Glossy, Positive, Color",
        Panoramas: "false",
      },
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "58",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          name: "debug album 3 (copy of 1)",
          id: "R6KJA",
          size: "0",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          name: "debug album",
          id: "GT7AG",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "ddf11cfc55671f90963001799d169807",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230825043525003",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      relatedFile: [
        { id: "bsnois71h91tddt49o0i700t2s", scheme: "image", name: "test.png", code: null },
        {
          id: "kmop1gc6951pf9964fu2ppem7a",
          scheme: "image",
          name: "image 1.png",
          code: null,
        },
        {
          id: "s3tou86kd97ed52q06qqgddk3l",
          scheme: "image",
          name: "image 1.png",
          code: null,
        },
      ],
      lastUploaded: "20230825043525003",
      created: "20230825043525003",
      time: "20230825043541601",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/nh9k9at5ad68h7sib9g6c3pl46/Bo-Tx4WCheY6TFDGdr8G27213v8/original?content-type=image%2Fpng&name=unhelpful_name.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=nh9k9at5ad68h7sib9g6c3pl46",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/nh9k9at5ad68h7sib9g6c3pl46/D1wzXdt-REjjZ43I3atI4dnwBxk/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "44",
      name: "unhelpful_name.png",
      default: {
        Size: "4895",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "44*58 Pixels",
        GPS: null,
        "Date uploaded": "20230825043525003",
        "Date modified": "20230825043541601",
        Name: "unhelpful_name.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-25 11:35:25",
        Resolution: "144",
      },
      id: "nh9k9at5ad68h7sib9g6c3pl46",
      size: "4895",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      metadata: {
        "Rendering Intent": "Perceptual",
        "Video Card Gamma": "(Binary data 48 bytes, use -b option to extract)",
        Compression: "Deflate/Inflate",
        "File Type Detail": "PNG",
        "File Type Extension": "png",
        "Profile ID": "0",
        "Profile Description ML (hi-IN)": "रंगीन LCD",
        "Pixel Units": "meters",
        "Profile Copyright": "Copyright Apple Inc., 2023",
        RDpi: "144",
        "X Resolution": "144",
        "Profile Date Time": "2023-06-22 09:28:22",
        "Profile File Signature": "acsp",
        "Profile Creator": "Apple Computer Inc.",
        WHRotated: "false",
        "Primary Platform": "Apple Computer Inc.",
        "CMM Flags": "Not Embedded, Independent",
        "Create Date": "2023-08-25 11:34:05",
        "Exif Byte Order": "Big-endian (Motorola, MM)",
        "User Comment": "Screenshot",
        "File Inode Change Date/Time": "2023-08-25 11:34:05",
        Color: "RGB",
        "Color Mode": "RGB",
        "Pixels Per Unit X": "5669",
        "File Type": "image",
        "Profile Version": "2.1.0",
        "Profile Description ML (fr-CA)": "ACL couleur",
        "Pixels Per Unit Y": "5669",
        "Color Model": "RGB",
        "Image Size": "54x48",
        "File Access Date/Time": "2023-08-25 11:34:05",
        Orientation: "Landscape File",
        "Profile Description ML (vi-VN)": "LCD Màu",
        "File Modification Date/Time": "2023-08-25 11:34:05",
        "Profile Description ML (en-GB)": "Colour LCD",
        Megapixels: "0.003",
        Interlace: "Noninterlaced",
        "Exif Image Height": "48",
        "Profile Description ML": "Color LCD",
        "Profile Connection Space": "XYZ",
        "Blue Matrix Column": "0.1571 0.06657 0.78407",
        "Y Resolution": "144",
        "Flight File Extension": "png",
        "Profile Description": "Display",
        "Profile Description ML (pt-PT)": "LCD a cores",
        "Device Manufacturer": "Apple Computer Inc.",
        "Color Space": "RGB",
        "Profile Name": "ICC Profile",
        RSize: "48",
        "Red Matrix Column": "0.51512 0.2412 -0.00105",
        "Flight File Type": "png",
        "File Name": "test.png",
        "Profile Class": "Display Device Profile",
        "Native Display Info": "(Binary data 62 bytes, use -b option to extract)",
        "Media White Point": "0.95045 1 1.08905",
        "Profile CMM Type": "Apple Computer Inc.",
        "Profile Description ML (es-XL)": "LCD color",
        "Bit Depth": "8",
        "Exif Image Width": "54",
        "Profile Description ML (en-AU)": "Colour LCD",
        "Image Height": "48",
        "Connection Space Illuminant": "0.9642 1 0.82491",
        "Image Width": "54",
        "Resolution Unit": "inches",
        "MIME Type": "image/png",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "4827",
        Filter: "Adaptive",
        "XMP Toolkit": "XMP Core 6.0.0",
        "Green Matrix Column": "0.29198 0.69225 0.04189",
        "Profile Description ML (fr-FR)": "LCD couleur",
        "Device Attributes": "Reflective, Glossy, Positive, Color",
        Panoramas: "false",
      },
      smartTags: ["Number", "Smoke Pipe", "Symbol", "Text"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "48",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/PMLQK",
          namePath: "debug folder/debug subfolder/debug album 2",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK" },
          width: "0",
          name: "debug album 2",
          id: "PMLQK",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "1d07abac2fc228093711159e4de23c98",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230825043405631",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      relatedFile: [
        {
          id: "nh9k9at5ad68h7sib9g6c3pl46",
          scheme: "image",
          name: "unhelpful_name.png",
          code: null,
        },
      ],
      lastUploaded: "20230825043405631",
      created: "20230825043405631",
      time: "20230825043426264",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/bsnois71h91tddt49o0i700t2s/h0TTQbSWQRKOg4NG7BaTcBTiGeo/original?content-type=image%2Fpng&name=test.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=bsnois71h91tddt49o0i700t2s",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/bsnois71h91tddt49o0i700t2s/4dQipJbWKjGBMFHDoB85dczEezE/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "54",
      name: "test.png",
      default: {
        Size: "4827",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "54*48 Pixels",
        GPS: null,
        "Date uploaded": "20230825043405631",
        "Date modified": "20230825043426264",
        Name: "test.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-25 11:34:05",
        Resolution: "144",
      },
      id: "bsnois71h91tddt49o0i700t2s",
      size: "4827",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      metadata: {
        "Rendering Intent": "Perceptual",
        "Video Card Gamma": "(Binary data 48 bytes, use -b option to extract)",
        Compression: "Deflate/Inflate",
        "File Type Detail": "PNG",
        "File Type Extension": "png",
        "Profile ID": "0",
        "Profile Description ML (hi-IN)": "रंगीन LCD",
        "Pixel Units": "meters",
        "Profile Copyright": "Copyright Apple Inc., 2023",
        RDpi: "144",
        "X Resolution": "144",
        "Profile Date Time": "2023-06-22 09:28:22",
        "Profile File Signature": "acsp",
        "Profile Creator": "Apple Computer Inc.",
        WHRotated: "false",
        "Primary Platform": "Apple Computer Inc.",
        "CMM Flags": "Not Embedded, Independent",
        "Create Date": "2023-08-18 14:38:41",
        "Exif Byte Order": "Big-endian (Motorola, MM)",
        "User Comment": "Screenshot",
        "File Inode Change Date/Time": "2023-08-18 14:38:41",
        Color: "RGB",
        "Color Mode": "RGB",
        "Pixels Per Unit X": "5669",
        "File Type": "image",
        "Profile Version": "2.1.0",
        "Profile Description ML (fr-CA)": "ACL couleur",
        "Pixels Per Unit Y": "5669",
        "Color Model": "RGB",
        "Image Size": "50x46",
        "File Access Date/Time": "2023-08-18 14:38:41",
        Orientation: "Landscape File",
        "Profile Description ML (vi-VN)": "LCD Màu",
        "File Modification Date/Time": "2023-08-18 14:38:41",
        "Profile Description ML (en-GB)": "Colour LCD",
        Megapixels: "0.002",
        Interlace: "Noninterlaced",
        "Exif Image Height": "46",
        "Profile Description ML": "Color LCD",
        "Profile Connection Space": "XYZ",
        "Blue Matrix Column": "0.1571 0.06657 0.78407",
        "Y Resolution": "144",
        "Flight File Extension": "png",
        "Profile Description": "Display",
        "Profile Description ML (pt-PT)": "LCD a cores",
        "Device Manufacturer": "Apple Computer Inc.",
        "Color Space": "RGB",
        "Profile Name": "ICC Profile",
        RSize: "46",
        "Red Matrix Column": "0.51512 0.2412 -0.00105",
        "Flight File Type": "png",
        "File Name": "image 1.png",
        "Profile Class": "Display Device Profile",
        "Native Display Info": "(Binary data 62 bytes, use -b option to extract)",
        "Media White Point": "0.95045 1 1.08905",
        "Profile CMM Type": "Apple Computer Inc.",
        "Profile Description ML (es-XL)": "LCD color",
        "Bit Depth": "8",
        "Exif Image Width": "50",
        "Profile Description ML (en-AU)": "Colour LCD",
        "Image Height": "46",
        "Connection Space Illuminant": "0.9642 1 0.82491",
        "Image Width": "50",
        "Resolution Unit": "inches",
        "MIME Type": "image/png",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "4600",
        Filter: "Adaptive",
        "XMP Toolkit": "XMP Core 6.0.0",
        "Green Matrix Column": "0.29198 0.69225 0.04189",
        "Profile Description ML (fr-FR)": "LCD couleur",
        "Device Attributes": "Reflective, Glossy, Positive, Color",
        Panoramas: "false",
      },
      smartTags: ["Number", "Symbol", "Text"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "46",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          name: "debug album",
          id: "GT7AG",
          size: "0",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/PMLQK",
          namePath: "debug folder/debug subfolder/debug album 2",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK" },
          width: "0",
          name: "debug album 2",
          id: "PMLQK",
          size: "0",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          name: "debug album 3 (copy of 1)",
          id: "R6KJA",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "0659f9f63704875b33d0f9536a01d234",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230818073841491",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      relatedFile: [
        {
          id: "nh9k9at5ad68h7sib9g6c3pl46",
          scheme: "image",
          name: "unhelpful_name.png",
          code: null,
        },
      ],
      lastUploaded: "20230818073841491",
      created: "20230818073841491",
      tag: ["debug tag"],
      time: "20230825040020641",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/XvnSinNZSFb3cJ5OSpCRZU4FQcA/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=kmop1gc6951pf9964fu2ppem7a",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/tPW11rvqDUjPj5_iWEE7VTLN9IU/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "50",
      name: "image 1.png",
      default: {
        Size: "4600",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "50*46 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841491",
        "Date modified": "20230825040020641",
        Name: "image 1.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "kmop1gc6951pf9964fu2ppem7a",
      size: "4600",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      metadata: {
        "Rendering Intent": "Perceptual",
        "Video Card Gamma": "(Binary data 48 bytes, use -b option to extract)",
        Compression: "Deflate/Inflate",
        "File Type Detail": "PNG",
        "File Type Extension": "png",
        "Profile ID": "0",
        "Profile Description ML (hi-IN)": "रंगीन LCD",
        "Pixel Units": "meters",
        "Profile Copyright": "Copyright Apple Inc., 2023",
        RDpi: "144",
        "X Resolution": "144",
        "Profile Date Time": "2023-06-22 09:28:22",
        "Profile File Signature": "acsp",
        "Profile Creator": "Apple Computer Inc.",
        WHRotated: "false",
        "Primary Platform": "Apple Computer Inc.",
        "CMM Flags": "Not Embedded, Independent",
        "Create Date": "2023-08-18 14:38:41",
        "Exif Byte Order": "Big-endian (Motorola, MM)",
        "User Comment": "Screenshot",
        "File Inode Change Date/Time": "2023-08-18 14:38:41",
        Color: "RGB",
        "Color Mode": "RGB",
        "Pixels Per Unit X": "5669",
        "File Type": "image",
        "Profile Version": "2.1.0",
        "Profile Description ML (fr-CA)": "ACL couleur",
        "Pixels Per Unit Y": "5669",
        "Color Model": "RGB",
        "Image Size": "58x54",
        "File Access Date/Time": "2023-08-18 14:38:41",
        Orientation: "Landscape File",
        "Profile Description ML (vi-VN)": "LCD Màu",
        "File Modification Date/Time": "2023-08-18 14:38:41",
        "Profile Description ML (en-GB)": "Colour LCD",
        Megapixels: "0.003",
        Interlace: "Noninterlaced",
        "Exif Image Height": "54",
        "Profile Description ML": "Color LCD",
        "Profile Connection Space": "XYZ",
        "Blue Matrix Column": "0.1571 0.06657 0.78407",
        "Y Resolution": "144",
        "Flight File Extension": "png",
        "Profile Description": "Display",
        "Profile Description ML (pt-PT)": "LCD a cores",
        "Device Manufacturer": "Apple Computer Inc.",
        "Color Space": "RGB",
        "Profile Name": "ICC Profile",
        RSize: "54",
        "Red Matrix Column": "0.51512 0.2412 -0.00105",
        "Flight File Type": "png",
        "File Name": "image 1.png",
        "Profile Class": "Display Device Profile",
        "Native Display Info": "(Binary data 62 bytes, use -b option to extract)",
        "Media White Point": "0.95045 1 1.08905",
        "Profile CMM Type": "Apple Computer Inc.",
        "Profile Description ML (es-XL)": "LCD color",
        "Bit Depth": "8",
        "Exif Image Width": "58",
        "Profile Description ML (en-AU)": "Colour LCD",
        "Image Height": "54",
        "Connection Space Illuminant": "0.9642 1 0.82491",
        "Image Width": "58",
        "Resolution Unit": "inches",
        "MIME Type": "image/png",
        "Finfotool version": "1.5",
        "Asset Data Size (Long)": "4728",
        Filter: "Adaptive",
        "XMP Toolkit": "XMP Core 6.0.0",
        "Green Matrix Column": "0.29198 0.69225 0.04189",
        "Profile Description ML (fr-FR)": "LCD couleur",
        "Device Attributes": "Reflective, Glossy, Positive, Color",
        Panoramas: "false",
      },
      smartTags: ["Symbol", "Triangle"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "54",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          name: "debug album",
          id: "GT7AG",
          size: "0",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          name: "debug album 3 (copy of 1)",
          id: "R6KJA",
          size: "0",
          scheme: "album",
        },
      ],
      md5: "4771d5f15000f379cfe409114ae0a109",
      versionHistory: [
        {
          no: "1",
          ownerName: "cmarsh@idems.international",
          created: "19691231160000000",
          time: "20230818073841173",
          versionId: "bGF0ZXN0X3ZlcnNpb25fdGFn",
          comment: null,
          uri: {
            preview:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/bGF0ZXN0X3ZlcnNpb25fdGFn/preview",
            download:
              "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/bGF0ZXN0X3ZlcnNpb25fdGFn",
          },
          currentVersion: true,
        },
      ],
      relatedFile: [
        {
          id: "nh9k9at5ad68h7sib9g6c3pl46",
          scheme: "image",
          name: "unhelpful_name.png",
          code: null,
        },
      ],
      lastUploaded: "20230818073841173",
      created: "20230818073841173",
      tag: ["debug tag", "debug tag 2"],
      time: "20230920081804212",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/1ULAyWL9Ig0e9pYFr77hTQP7y4c/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=s3tou86kd97ed52q06qqgddk3l",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/k-byeOYHEBlQr2edf72Px9u1BGI/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/LowJPG",
      },
      additional: {
        "Data Type": null,
        Platform: ["ParentApp"],
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "58",
      name: "image 1.png",
      default: {
        Size: "4728",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "58*54 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841173",
        "Date modified": "20230920081804212",
        Name: "image 1.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "s3tou86kd97ed52q06qqgddk3l",
      size: "4728",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
  ],
};
