// Response from querying "Search under folder"
export default {
  facets: [
    { name: "meta_multichoice_11" },
    { name: "fileType", value: ["PNG", "SVG"] },
    { mix: 144, max: 144, min: 144, name: "resolution" },
    {
      mix: 9223372036854775807,
      max: -9223372036854775808,
      min: 9223372036854775807,
      name: "duration",
    },
    { name: "meta_choice_14" },
    { name: "tags", value: ["Untagged", "debug tag", "debug tag 2"] },
    { name: "keywords", value: ["Unkeyworded"] },
    { mix: 1692961220, max: 1695223084, min: 1692961220, name: "lastModified" },
    { mix: 44, max: 934, min: 44, name: "dimension" },
    { name: "meta_choice_10" },
    { name: "meta_multichoice_5" },
    { name: "owner", value: ["cmarsh@idems.international"] },
    { name: "meta_multichoice_6" },
    { name: "meta_multichoice_3", value: ["ParentApp"] },
    { name: "orientation", value: ["Landscape", "Portrait"] },
    { name: "meta_multichoice_4" },
    { name: "meta_choice_9" },
    { name: "storageClass", value: ["standard"] },
    { name: "meta_multichoice_1" },
    { name: "meta_multichoice_2" },
    { name: "approval", value: ["Approved"] },
    { mix: 1692369521, max: 1695217506, min: 1692369521, name: "created" },
    { name: "meta_multichoice_0" },
    { name: "scheme", value: ["image"] },
    { name: "meta_multichoice_8" },
    { mix: 4600, max: 11678, min: 4600, name: "fileSize" },
    { name: "meta_choice_3" },
    { name: "meta_choice_0" },
    {
      mix: 9223372036854775807,
      max: -9223372036854775808,
      min: 9223372036854775807,
      name: "pageNumber",
    },
  ],
  matchExpr: "es",
  results: [
    {
      smartTags: [
        "Adult",
        "Dress",
        "Face",
        "Female",
        "Head",
        "Lady",
        "Long Sleeve",
        "Person",
        "Sleeve",
        "Woman",
      ],
      ownerName: "cmarsh@idems.international",
      dpi: "72",
      height: "2580",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/S9CBS/H45JP/JN6JU/TDEJQ",
          namePath: "debug folder/ParentApp for Teens TZ/images/characters/neighbour",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/TDEJQ" },
          width: "0",
          id: "TDEJQ",
          scheme: "album",
        },
      ],
      md5: "8872a54ec15b8148b36382c161721d4e",
      tag: ["Untagged"],
      time: "20230920064506000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/383q8ogklt5ft4ckadacjj826b/pYIoWOvLyezOQNIj_3cnCRFRz9w/original?content-type=image%2Fsvg%2Bxml&name=neutral.svg",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=383q8ogklt5ft4ckadacjj826b",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/383q8ogklt5ft4ckadacjj826b/gnaIz3qbZocX0cSDAyr3Qmc4PbU/m800/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/383q8ogklt5ft4ckadacjj826b/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "934",
      name: "neutral.svg",
      default: {
        Size: "11678",
        Color: null,
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "934*2580 Pixels",
        GPS: null,
        "Date uploaded": "20230920064506000",
        "Date modified": "20230920064506000",
        Name: "1a07a46214af4afe91945354c9cd02cb",
        "Modified by": null,
        "Content Type": "image/svg+xml",
        Author: null,
        "Date Created": "2023-09-20 13:45:06",
        Resolution: null,
      },
      id: "383q8ogklt5ft4ckadacjj826b",
      size: "11678",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      smartTags: ["Untagged"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "58",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          id: "GT7AG",
          scheme: "album",
        },
      ],
      md5: "ddf11cfc55671f90963001799d169807",
      tag: ["Untagged"],
      time: "20230920035915000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/vil7vn2g513ajfcr2ppgmd5c0a/ylpbwhrK2M8BLdjdt7PMchPk4tk/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=vil7vn2g513ajfcr2ppgmd5c0a",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/vil7vn2g513ajfcr2ppgmd5c0a/xTtaCIRdgRgpy3WR_ZpLidb9Ng4/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/vil7vn2g513ajfcr2ppgmd5c0a/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "44",
      name: "image 1.png",
      default: {
        Size: "4895",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "44*58 Pixels",
        GPS: null,
        "Date uploaded": "20230920035915000",
        "Date modified": "20230920035949000",
        Name: "fcaa7fdc502846a9bd9b16730b34ac0a",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-09-20 10:59:15",
        Resolution: "144",
      },
      id: "vil7vn2g513ajfcr2ppgmd5c0a",
      size: "4895",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      smartTags: ["Untagged"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "58",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          id: "R6KJA",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          id: "GT7AG",
          scheme: "album",
        },
      ],
      md5: "ddf11cfc55671f90963001799d169807",
      tag: ["Untagged"],
      time: "20230825043525000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/nh9k9at5ad68h7sib9g6c3pl46/Bo-Tx4WCheY6TFDGdr8G27213v8/original?content-type=image%2Fpng&name=unhelpful_name.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=nh9k9at5ad68h7sib9g6c3pl46",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/nh9k9at5ad68h7sib9g6c3pl46/D1wzXdt-REjjZ43I3atI4dnwBxk/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/nh9k9at5ad68h7sib9g6c3pl46/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "44",
      name: "unhelpful_name.png",
      default: {
        Size: "4895",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "44*58 Pixels",
        GPS: null,
        "Date uploaded": "20230825043525000",
        "Date modified": "20230825043541000",
        Name: "bc5344aba5534c889f925a60660f3586",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-25 11:35:25",
        Resolution: "144",
      },
      id: "nh9k9at5ad68h7sib9g6c3pl46",
      size: "4895",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      smartTags: ["Number", "Smoke Pipe", "Symbol", "Text"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "48",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/PMLQK",
          namePath: "debug folder/debug subfolder/debug album 2",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK" },
          width: "0",
          id: "PMLQK",
          scheme: "album",
        },
      ],
      md5: "1d07abac2fc228093711159e4de23c98",
      tag: ["Untagged"],
      time: "20230825043405000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/bsnois71h91tddt49o0i700t2s/h0TTQbSWQRKOg4NG7BaTcBTiGeo/original?content-type=image%2Fpng&name=test.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=bsnois71h91tddt49o0i700t2s",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/bsnois71h91tddt49o0i700t2s/4dQipJbWKjGBMFHDoB85dczEezE/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/bsnois71h91tddt49o0i700t2s/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "54",
      name: "test.png",
      default: {
        Size: "4827",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "54*48 Pixels",
        GPS: null,
        "Date uploaded": "20230825043405000",
        "Date modified": "20230825043426000",
        Name: "5f2f8970e18a43d6b7a44e0123801d5c",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-25 11:34:05",
        Resolution: "144",
      },
      id: "bsnois71h91tddt49o0i700t2s",
      size: "4827",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      smartTags: ["Number", "Symbol", "Text"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "46",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          id: "R6KJA",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/PMLQK",
          namePath: "debug folder/debug subfolder/debug album 2",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK" },
          width: "0",
          id: "PMLQK",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          id: "GT7AG",
          scheme: "album",
        },
      ],
      md5: "0659f9f63704875b33d0f9536a01d234",
      tag: ["debug tag"],
      time: "20230818073841000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/XvnSinNZSFb3cJ5OSpCRZU4FQcA/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=kmop1gc6951pf9964fu2ppem7a",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/tPW11rvqDUjPj5_iWEE7VTLN9IU/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/LowJPG",
      },
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "50",
      name: "image 1.png",
      default: {
        Size: "4600",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "50*46 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841000",
        "Date modified": "20230825040020000",
        Name: "a5b190c186494397a52623fc2ce5d6ea",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "kmop1gc6951pf9964fu2ppem7a",
      size: "4600",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
    {
      smartTags: ["Symbol", "Triangle"],
      ownerName: "cmarsh@idems.international",
      dpi: "144",
      height: "54",
      approvalStatus: "Approved",
      relatedAlbums: [
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
          id: "R6KJA",
          scheme: "album",
        },
        {
          dpi: "72",
          height: "0",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
          id: "GT7AG",
          scheme: "album",
        },
      ],
      md5: "4771d5f15000f379cfe409114ae0a109",
      tag: ["debug tag", "debug tag 2"],
      time: "20230818073841000",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/1ULAyWL9Ig0e9pYFr77hTQP7y4c/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=s3tou86kd97ed52q06qqgddk3l",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/k-byeOYHEBlQr2edf72Px9u1BGI/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/LowJPG",
      },
      additional: {
        "Data Type": null,
        Platform: ["ParentApp"],
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      width: "58",
      name: "image 1.png",
      default: {
        Size: "4728",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "58*54 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841000",
        "Date modified": "20230920081804000",
        Name: "e0fb8f20d46a4ee6945a01b5a835b475",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "s3tou86kd97ed52q06qqgddk3l",
      size: "4728",
      scheme: "image",
      owner: "cmarsh@idems.international",
    },
  ],
  found: 6,
  sortBy: "time",
  sortDirection: "descending",
  limit: 100,
};
