export default {
  facets: [
    { name: "meta_multichoice_11" },
    { name: "fileType", value: ["PNG"] },
    { min: 144, mix: 144, name: "resolution", max: 144 },
    {
      min: 9223372036854775807,
      mix: 9223372036854775807,
      name: "duration",
      max: -9223372036854775808,
    },
    { name: "meta_choice_14" },
    { name: "tags", value: ["Untagged", "debug tag", "debug tag 2"] },
    { name: "keywords", value: ["Unkeyworded"] },
    { min: 1692961094, mix: 1692961094, name: "lastModified", max: 1695223084 },
    { min: 46, mix: 46, name: "dimension", max: 54 },
    { name: "meta_choice_10" },
    { name: "meta_multichoice_5" },
    { name: "owner", value: ["cmarsh@idems.international"] },
    { name: "meta_multichoice_6" },
    { name: "meta_multichoice_3", value: ["ParentApp"] },
    { name: "orientation", value: ["Landscape"] },
    { name: "meta_multichoice_4" },
    { name: "meta_choice_9" },
    { name: "storageClass", value: ["standard"] },
    { name: "meta_multichoice_1" },
    { name: "meta_multichoice_2" },
    { name: "approval", value: ["Approved"] },
    { min: 1692369442, mix: 1692369442, name: "created", max: 1692962899 },
    { name: "meta_multichoice_0" },
    { name: "scheme", value: ["album", "folder", "image"] },
    { name: "meta_multichoice_8" },
    { name: "fileSize", max: 4728 },
    { name: "meta_choice_3" },
    { name: "meta_choice_0" },
    {
      min: 9223372036854775807,
      mix: 9223372036854775807,
      name: "pageNumber",
      max: -9223372036854775808,
    },
  ],
  matchExpr: "es",
  results: [
    {
      height: "46",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Untagged"],
      dpi: "72",
      idPath: "V0DQB/KRSIO/PMLQK",
      namePath: "debug folder/debug subfolder/debug album 2",
      tag: ["Untagged"],
      time: "20230825042819000",
      name: "debug album 2",
      id: "PMLQK",
      size: "2",
      scheme: "album",
      owner: "cmarsh@idems.international",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/preview",
        detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK",
      },
      width: "50",
    },
    {
      height: "0",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Untagged"],
      dpi: "72",
      idPath: "V0DQB/KRSIO",
      namePath: "debug folder/debug subfolder",
      tag: ["Untagged"],
      time: "20230825042808000",
      name: "debug subfolder",
      id: "KRSIO",
      size: "5",
      scheme: "folder",
      owner: "cmarsh@idems.international",
      url: { detail: "https://parentingforlifelonghealth.canto.com/folder/KRSIO" },
      width: "0",
    },
    {
      height: "0",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Untagged"],
      dpi: "72",
      idPath: "V0DQB",
      namePath: "debug folder",
      tag: ["Untagged"],
      time: "20230825035814000",
      description: "A folder created for debugging functionality",
      name: "debug folder",
      id: "V0DQB",
      size: "10",
      scheme: "folder",
      owner: "cmarsh@idems.international",
      url: { detail: "https://parentingforlifelonghealth.canto.com/folder/V0DQB" },
      width: "0",
    },
    {
      height: "54",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Untagged"],
      dpi: "72",
      idPath: "V0DQB/GT7AG",
      namePath: "debug folder/debug album",
      tag: ["Untagged"],
      time: "20230818073722000",
      description: "An album to test functionality",
      name: "debug album",
      id: "GT7AG",
      size: "4",
      scheme: "album",
      owner: "cmarsh@idems.international",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/preview",
        detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG",
      },
      width: "58",
    },
    {
      height: "54",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Untagged"],
      dpi: "72",
      idPath: "V0DQB/KRSIO/R6KJA",
      namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
      tag: ["Untagged"],
      time: "20230818073722000",
      description: "An album to test functionality",
      name: "debug album 3 (copy of 1)",
      id: "R6KJA",
      size: "3",
      scheme: "album",
      owner: "cmarsh@idems.international",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/preview",
        detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA",
      },
      width: "58",
    },
    {
      height: "46",
      relatedAlbums: [
        {
          height: "0",
          dpi: "72",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          id: "R6KJA",
          scheme: "album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
        },
        {
          height: "0",
          dpi: "72",
          idPath: "V0DQB/KRSIO/PMLQK",
          namePath: "debug folder/debug subfolder/debug album 2",
          id: "PMLQK",
          scheme: "album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/PMLQK" },
          width: "0",
        },
        {
          height: "0",
          dpi: "72",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          id: "GT7AG",
          scheme: "album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
        },
      ],
      md5: "0659f9f63704875b33d0f9536a01d234",
      approvalStatus: "Approved",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Number", "Symbol", "Text"],
      dpi: "144",
      tag: ["debug tag"],
      time: "20230818073841000",
      additional: {
        "Data Type": null,
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      name: "image 1.png",
      default: {
        Size: "4600",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "50*46 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841000",
        "Date modified": "20230825040020000",
        Name: "image 1.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "kmop1gc6951pf9964fu2ppem7a",
      size: "4600",
      scheme: "image",
      owner: "cmarsh@idems.international",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/XvnSinNZSFb3cJ5OSpCRZU4FQcA/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=kmop1gc6951pf9964fu2ppem7a",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/kmop1gc6951pf9964fu2ppem7a/tPW11rvqDUjPj5_iWEE7VTLN9IU/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/kmop1gc6951pf9964fu2ppem7a/LowJPG",
      },
      width: "50",
    },
    {
      height: "54",
      relatedAlbums: [
        {
          height: "0",
          dpi: "72",
          idPath: "V0DQB/KRSIO/R6KJA",
          namePath: "debug folder/debug subfolder/debug album 3 (copy of 1)",
          id: "R6KJA",
          scheme: "album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/R6KJA" },
          width: "0",
        },
        {
          height: "0",
          dpi: "72",
          idPath: "V0DQB/GT7AG",
          namePath: "debug folder/debug album",
          id: "GT7AG",
          scheme: "album",
          url: { detail: "https://parentingforlifelonghealth.canto.com/album/GT7AG" },
          width: "0",
        },
      ],
      md5: "4771d5f15000f379cfe409114ae0a109",
      approvalStatus: "Approved",
      ownerName: "cmarsh@idems.international",
      smartTags: ["Symbol", "Triangle"],
      dpi: "144",
      tag: ["debug tag", "debug tag 2"],
      time: "20230818073841000",
      additional: {
        "Data Type": null,
        Platform: ["ParentApp"],
        Year: null,
        "Product Type": null,
        "Number of In-Person Sessions": null,
        "Child Gender": null,
        "Programme Delivery Format": null,
        "Caregiver Gender": null,
      },
      name: "image 1.png",
      default: {
        Size: "4728",
        Color: "RGB",
        "Uploaded by": "cmarsh@idems.international",
        Dimensions: "58*54 Pixels",
        GPS: null,
        "Date uploaded": "20230818073841000",
        "Date modified": "20230920081804000",
        Name: "image 1.png",
        "Modified by": "cmarsh@idems.international",
        "Content Type": "image/png",
        Author: null,
        "Date Created": "2023-08-18 14:38:41",
        Resolution: "144",
      },
      id: "s3tou86kd97ed52q06qqgddk3l",
      size: "4728",
      scheme: "image",
      owner: "cmarsh@idems.international",
      url: {
        preview:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/preview",
        download:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l",
        metadata:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/metadata",
        HighJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/HighJPG",
        PNG: "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/PNG",
        directUrlOriginal:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/1ULAyWL9Ig0e9pYFr77hTQP7y4c/original?content-type=image%2Fpng&name=image+1.png",
        detail:
          "https://parentingforlifelonghealth.canto.com/smartalbum/image?column=image&id=s3tou86kd97ed52q06qqgddk3l",
        directUrlPreview:
          "https://parentingforlifelonghealth.canto.com/direct/image/s3tou86kd97ed52q06qqgddk3l/k-byeOYHEBlQr2edf72Px9u1BGI/m0/800",
        LowJPG:
          "https://parentingforlifelonghealth.canto.com/api_binary/v1/image/s3tou86kd97ed52q06qqgddk3l/LowJPG",
      },
      width: "58",
    },
  ],
  found: 7,
  sortBy: "time",
  sortDirection: "descending",
  limit: 100,
};
