nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

# Custom script using post-install plugin to compile sources after install
# NOTE - currently this happens without output to terminal (issue)
postinstall: yarn precompile && yarn workflow populate_src_assets

# Ignore some common warnings https://yarnpkg.com/advanced/error-codes
logFilters:
  - code: "YN0076" # INCOMPATIBLE_ARCHITECTURE
    level: "discard"
  - code: "YN0060" # INCOMPATIBLE_PEER_DEPENDENCY
    level: "discard"
  - code: "YN0002" # MISSING_PEER_DEPENDENCY
    level: "discard"
