# Sync hardcoded labels with github

# NOTE - It's also possible to sync labels across repos via cli, which could be used instead of this action
# https://cli.github.com/manual/gh_label_clone

name: Github Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          