##################################################################################
#         About
##################################################################################
# Reuseable workflow to be called from content repos.
# Build and deploy app bundle for ios
#
#         Version : 1.1
#
##################################################################################
#         Configuration
##################################################################################
env:
  DEPLOYMENT_NAME: ${{vars.DEPLOYMENT_NAME}}
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
  APP_CODE_BRANCH: ${{vars.APP_CODE_BRANCH}}
  PARENT_DEPLOYMENT_REPO: ${{vars.PARENT_DEPLOYMENT_REPO}}
  PARENT_DEPLOYMENT_NAME: ${{vars.PARENT_DEPLOYMENT_NAME}}
  PARENT_DEPLOYMENT_BRANCH: ${{vars.PARENT_DEPLOYMENT_BRANCH}}

  GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}

  IOS_CODE_SIGNING_IDENTITY: ${{ secrets.IOS_CODE_SIGNING_IDENTITY }}
  IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}

  IOS_MOBILEPROVISION_BASE64: ${{secrets.IOS_MOBILEPROVISION_BASE64}}
  IOS_P12_BASE64: ${{secrets.IOS_P12_BASE64}}

  ##################################################################################
  #         Main Code
  ##################################################################################
name:
  IOS Build

  # Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
  group: ios-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: "Specify branch for deployment"
        default: ""
    secrets:
      DEPLOYMENT_PRIVATE_KEY:
        description: Provide private key if deployment uses encrypted config

jobs:
  #############################################################################
  #         Deployment build
  #############################################################################

  #   build_web:
  #     uses: ./.github/workflows/reusable-app-build.yml
  #     with:
  #       branch: ${{ inputs.branch }}
  #       post-build-cmd: npx cap sync ios
  #       additional-artifact: ios
  #     secrets: inherit

  debug:
    runs-on: ubuntu-latest
    # needs: build_web
    steps:
      - name: Download IOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ios
          # TODO - revert after debugging   
          run-id: 13727815102
      - name: Extract Build folder
        run: |
          mkdir ios
          tar -xf artifact.tar --directory ios
          ls
          ls ios
          ls ios/App

        # TODO - google plist
      #   - name: Populate google-services.json
      #     env:
      #       GOOGLE_SERVICES_JSON: ${{ env.GOOGLE_SERVICES_JSON }}
      #     run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json

    #############################################################################
    #         IOS Build and Upload
    #############################################################################

    #   - name: Upload application
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: app
    #       path: ${{ runner.temp }}/build/app.ipa
    #       # you can also archive the entire directory
    #       # path: ${{ runner.temp }}/build
    #       retention-days: 3
