##################################################################################
#         About
##################################################################################
# Reuseable workflow to be called from content repos.
# Build and deploy app bundle for ios
#
#         Version : 1.1
#
##################################################################################
#         Configuration
##################################################################################
env:
  DEPLOYMENT_NAME: ${{vars.DEPLOYMENT_NAME}}
  DEPLOYMENT_PRIVATE_KEY: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
  APP_CODE_BRANCH: ${{vars.APP_CODE_BRANCH}}
  PARENT_DEPLOYMENT_REPO: ${{vars.PARENT_DEPLOYMENT_REPO}}
  PARENT_DEPLOYMENT_NAME: ${{vars.PARENT_DEPLOYMENT_NAME}}
  PARENT_DEPLOYMENT_BRANCH: ${{vars.PARENT_DEPLOYMENT_BRANCH}}

  GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}

  IOS_CODE_SIGNING_IDENTITY: ${{ secrets.IOS_CODE_SIGNING_IDENTITY }}
  IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}

  IOS_MOBILEPROVISION_BASE64: ${{secrets.IOS_MOBILEPROVISION_BASE64}}
  IOS_P12_BASE64: ${{secrets.IOS_P12_BASE64}}

  ##################################################################################
  #         Main Code
  ##################################################################################
name:
  IOS Build

  # Only keep one active build per ref (e.g. pr branch, push branch, triggering workflow ref)
concurrency:
  group: ios-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: "Specify branch for deployment"
        default: ""
    secrets:
      DEPLOYMENT_PRIVATE_KEY:
        description: Provide private key if deployment uses encrypted config

jobs:
  #############################################################################
  #         Deployment build
  #############################################################################

  build_web:
    uses: ./.github/workflows/reusable-app-build.yml
    with:
      branch: ${{ inputs.branch }}
      post-build-cmd: yarn workflow ios configure && npx cap sync ios
      additional-artifact: ios
      # Ensure build also run on macos to allow npx cap sync to configure ios pods
      workflow-runner: macos-latest
    secrets: inherit

  debug:
    runs-on: macos-latest
    needs: build_web
    steps:
      - name: Download IOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ios
          # TODO - revert after debugging
          #   NOTE - need to explicitly include token to download from a different workflow run
          # https://github.com/actions/download-artifact/issues/320
          github-token: ${{ github.token }}
          # run-id: 13731930921

      - name: Extract Build folder
        run: |
          mkdir ios
          tar -xf artifact.tar --directory ios
          ls ios

      # Create a ruby gemfile declaring fastlane dep for install. This will be auto-installed
      # via the setup-ruby command. This file could also be created and committed to core repo is required
      - name: Add fastlane gem
        working-directory: ios/App
        run: |
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "fastlane"' >> Gemfile
          cat Gemfile

      # Setup ruby. Use bundler-cache to auto-install Gemfile in working directory
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          working-directory: ios/App

      # Call fastlane build_ios_app track
      # https://docs.fastlane.tools/actions/build_ios_app/
      - name: Build IOS
        env:
          configuration: debug
          sdk: "iOS 11.1"
        working-directory: ios/App
        run: |
          bundle exec fastlane run build_ios_app
          --configuration "${{env.configuration}}"
          --scheme "App"
          --output_name "app.ipa"
          --sdk "${{env.sdk}}"

    # TODO - google plist
    #   - name: Populate google-services.json
    #     env:
    #       GOOGLE_SERVICES_JSON: ${{ env.GOOGLE_SERVICES_JSON }}
    #     run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json

    #############################################################################
    #         IOS Build and Upload
    #############################################################################

    #   - name: Upload application
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: app
    #       path: ${{ runner.temp }}/build/app.ipa
    #       # you can also archive the entire directory
    #       # path: ${{ runner.temp }}/build
    #       retention-days: 3
